#!/usr/bin/env bash
# Generates docs/reference/workflows.md from the workflow_call inputs of the
# reusable workflows, so the reference cannot drift from the code.
# Usage: scripts/gen-workflow-reference.sh > docs/reference/workflows.md
set -euo pipefail

# Two incompatible yq implementations exist; only use them to convert to JSON.
if yq --version 2>&1 | grep -qi mikefarah; then
  to_json() { yq -o=json '.' "$1"; }
else
  to_json() { yq '.' "$1"; }
fi

cat << 'HEADER'
# Reusable workflows reference

<!-- Generated by scripts/gen-workflow-reference.sh: do not edit by hand. -->

Neither workflow exposes outputs: the result is the job status. On GitHub,
zizmor also uploads SARIF results to Code Scanning.
HEADER

for wf in validate-helm zizmor; do
  printf '\n## `%s.yml`\n\n' "$wf"
  printf '| Input | Type | Required | Default | Description |\n|---|---|---|---|---|\n'
  to_json ".github/workflows/${wf}.yml" | jq -r '
    (.on // .["true"] // {}).workflow_call.inputs // {} | to_entries[]
    | "| `\(.key)` | \(.value.type) | \(.value.required // false) | `\(.value.default // "")` | \((.value.description // "") | gsub("\n"; " ") | gsub("\\s+$"; "")) |"'
done
